config/routes.rb
Rails.application.routes.draw do
  resources :routings
  resources :timelines
  resources :collect_criterions

  resources :collects do 
    member do 
      get 'timeline'
    end
  end
  resources :criterions
  resources :commissions
  resources :areas do 
    collection do 
      get 'export'
      get 'export_detail'
    end
  end

  resources :stations do 
    member do 
      get 'area'
    end
    collection do 
      get 'export'
    end
  end
  resources :cities do 
    member do 
      get 'map'
    end
  end
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  get  '/operate' => 'home#operate'
  post '/import' => 'home#import'   
  get '/clear' => 'home#clear'   

  authenticated :admin do
    root "admin/keys#index", as: "admin_root"
  end
  authenticated :users do
    root "stations#index", as: "users_root"
  end

  namespace :admin do 
    resources :keys
    resources :stations do 
      collection do 
        get 'syn'
      end 
    end
  end
  mount ApiV1 => "/" 
  mount GrapeSwaggerRails::Engine => '/swagger'
 

end

app/views/shared/_admin_navbar.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container
      .navbar-header
          = link_to "我的@蔚县", root_url, class: "navbar-brand"
          button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'
                span.icon-bar
                span.icon-bar
                span.icon-bar
                span.icon-bar
      div class="collapse navbar-collapse"
         ul class="nav navbar-nav"
            li class="#{(params[:controller].end_with?('information') or params[:controller].end_with?('home'))? 'active':'' }"
              = link_to "信息", admin_information_index_path
            li class="#{params[:controller].end_with?('shops')?  'active':'' }"
              = link_to "商店",  admin_shops_path
            li class="#{params[:controller].end_with?('users')?  'active':'' }"
              = link_to "用户",  admin_users_path
            li class="#{params[:controller].end_with?('categories')?  'active':'' }"
              = link_to "类别",  admin_categories_path
         ul class="nav navbar-nav navbar-right"
            div class="collapse navbar-collapse"
               ul class="nav navbar-nav"

               ul class="nav navbar-nav navbar-right"
                  - if admin_signed_in?
                    li
                        = link_to "退出", destroy_admin_session_path, method: "delete"
                  - else
                    li
                        = link_to "注册", new_admin_registration_path
                    li
                        = link_to "登陆", new_admin_session_path

app/views/shared/_api_base.html.slim
input type="hidden" id="api-base-url" value="#{Settings.api_base_url}"
input type="hidden" id="app_key" value="#{Settings.app_key}"

app/views/shared/_baidu_map_assets.html.slim
//
  = javascript_include_tag '//api.map.baidu.com/api?v=2.0&ak=00bf4cd7474f3f7dea81118417aa3c88', 'data-turbolinks-track' => true
// = javascript_include_tag 'http://api.map.baidu.com/getscript?v=2.0&ak=00bf4cd7474f3f7dea81118417aa3c88&services=&t=20150522094656', 'data-turbolinks-track' => true
//
  = javascript_include_tag '//api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js', 'data-turbolinks-track' => true

//
  = stylesheet_link_tag    '//api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.css', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag '//api.map.baidu.com/library/SearchInfoWindow/1.4/src/SearchInfoWindow_min.js', 'data-turbolinks-track' => true
//
  = javascript_include_tag '//api.map.baidu.com/library/GeoUtils/1.2/src/GeoUtils_min.js', 'data-turbolinks-track' => true
  = stylesheet_link_tag    '//api.map.baidu.com/library/SearchInfoWindow/1.4/src/SearchInfoWindow_min.css', media: 'all', 'data-turbolinks-track' => true

app/views/shared/_brand.html.slim
nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation"
    .container-fluid
      .navbar-header
          = link_to "蔚县@我", root_url, class: "navbar-brand"

app/views/shared/_flash_messages.html.slim
- if flash.keys.size > 0
  .flash-message
    - flash.keys.each do |key|
            .alert class="alert-#{key}"
              = flash[key]
              button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;

app/views/shared/_footer.html.slim
.footer
    hr
    .container
       p.text-muted.text-center
          span.text-danger
              strong
                 | 移动科技创意生活！

app/views/shared/_ie9.html.slim
/[if lt IE 9]
   script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
   script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"
   link href="http://static.yuxian.me/respond-proxy.html" id="respond-proxy" rel="respond-proxy"
   link href="/respond.proxy.gif" id="respond-redirect" rel="respond-redirect"
   script src="/respond.proxy.js"

/[if IE 10]
   = javascript_include_tag 'ie10-viewport-bug-workaround'
/[if IE]
   = javascript_include_tag 'ie-emulation-modes-warning'

app/views/shared/_ie_tip.html.slim
/[if lt IE 9]
  .container
    .row
      .col-lg-12
        p.alert.alert-warning
          | 十分抱歉，本站为提供更好的服务，不能很好的支持您正在使用的浏览器浏览本站，建议使用
          span.text-danger  
            strong IE9以上版本，或Chrome，FireFox 等浏览器最新版本，
          span.text-success
            | 可通过搜狗，百度等搜索下载

app/views/shared/_logo.html.slim
.logo
  = image_tag "logo.png", class: "logo-img"

app/views/shared/_meta.html.slim
meta name="baidu-site-verification" content="hov3MzmVz6"
- if content_for?(:title)
    = yield :title
- else
    title = "定价"
meta name="keywords" content="#{meta_keywords}"
meta name="description" content="#{meta_description}"

meta charset='utf-8'
meta http-equiv='X-UA-Compatible' content='IE=edge'
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"
meta name="apple-mobile-web-app-capable" content="yes"
meta name="mobile-web-app-capable" content="yes"
meta name="apple-mobile-web-app-title" content="定价"
meta content="email=no" name="format-detection"
meta property='wb:webmaster' content="78e9f2e1c609997f"


// = favicon_link_tag 'logo.jpg'

app/views/shared/_navbar.html.slim
nav id="navbar" class="navbar navbar-inverse navbar-fixed-bottom" role="navigation"
    .container
      .navbar-header
        button(class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar")
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"

app/views/shared/_notice.html.slim
.container
  .row
    .col-md-12
        //
          - unless notice.blank?
            p class="notice alert alert-info"
                = notice
        - unless alert.blank?
          p class="alert alert-warning"
              = alert

app/views/shared/_session_navbar.html.slim
nav id="navbar" class="navbar navbar-fixed-top navbar-inverse" role="navigation"
    .container-fluid
      .navbar-header
          = image_tag "logo.png", class: "logo-img"

      div class="collapse navbar-collapse"
         ul class="nav navbar-nav navbar-right"
          //
            - if admin_signed_in?
                li
                  = link_to "退出", destroy_admin_session_url, method: "delete"
            - if user_signed_in?
                li
                  = link_to "退出", destroy_user_session_url, method: "delete"

app/views/shared/_sidebar.html.slim
ul.nav.nav-sidebar 
 li class="#{params[:controller].end_with?('collect_criterions')? 'active':''}"
   = link_to "时长标准", collect_criterions_path
 
 li class="#{params[:controller].end_with?('collects')? 'active':''}"
   = link_to "揽件预警", collects_path
 li class="#{params[:controller].end_with?('routings')? 'active':''}"
   = link_to "路由设置", routings_path