config/routes.rb
Rails.application.routes.draw do
  resources :routings
  resources :timelines
  resources :collect_criterions

  resources :collects do 
    member do 
      get 'timeline'
    end
  end
  resources :criterions
  resources :commissions
  resources :areas do 
    collection do 
      get 'export'
      get 'export_detail'
    end
  end

  resources :stations do 
    member do 
      get 'area'
    end
    collection do 
      get 'export'
    end
  end
  resources :cities do 
    member do 
      get 'map'
    end
  end
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  get  '/operate' => 'home#operate'
  post '/import' => 'home#import'   
  get '/clear' => 'home#clear'   

  authenticated :admin do
    root "admin/keys#index", as: "admin_root"
  end
  authenticated :users do
    root "stations#index", as: "users_root"
  end

  namespace :admin do 
    resources :keys
    resources :stations do 
      collection do 
        get 'syn'
      end 
    end
  end
  mount ApiV1 => "/" 
  mount GrapeSwaggerRails::Engine => '/swagger'
 

end

app/models/routing.rb
class Routing < ActiveRecord::Base
  belongs_to :start_province, class_name: "Province", foreign_key: "start_province_id"
  belongs_to :start_city, class_name: "City", foreign_key: "start_city_id"
  belongs_to :start_department, class_name: "Department", foreign_key: "start_department_id"
  belongs_to :destination_province, class_name: "Province", foreign_key: "destination_province_id"
  belongs_to :destiantion_city, class_name: "City", foreign_key: "destination_city_id"
  belongs_to :destiantion_department, class_name: "Department", foreign_key: "destination_department_id"
end

app/controllers/routings_controller.rb
class RoutingsController < ApplicationController
  before_action :set_routing, only: [:show, :edit, :update, :destroy]

  # GET /routings
  def index
    @routings = Routing.all
  end

  # GET /routings/1
  def show
  end

  # GET /routings/new
  def new
    @routing = Routing.new
  end

  # GET /routings/1/edit
  def edit
  end

  # POST /routings
  def create
    @routing = Routing.new(routing_params)

    if @routing.save
      redirect_to @routing, notice: 'Routing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /routings/1
  def update
    if @routing.update(routing_params)
      redirect_to @routing, notice: 'Routing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /routings/1
  def destroy
    @routing.destroy
    redirect_to routings_url, notice: 'Routing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routing
      @routing = Routing.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def routing_params
      params.require(:routing).permit(:shift, :start_at, :collect_mins, :in_mins, 
                                      :out_mins, :arrival_mins, :start_province_id, :start_city_id, 
                                      :start_city_id,:start_department_id, 
                                      :destination_province_id, :destination_city_id, :destination_department_id)
    end
end

app/views/routings/_form.html.slim
= simple_form_for(@routing) do |f|
  = f.error_notification
  .row
    .col-md-3.col-md-offset-3
      p.text-center 开始
      = f.input :start_province_id, collection: Province.all
      = f.input :start_city_id, collection: City.all
      = f.input :start_department_id, collection: Department.all
    .col-md-3
      p.text-center 目的地
      = f.input :destination_province_id, collection: Province.all
      = f.input :destination_city_id, collection: City.all
      = f.input :destination_department_id, collection: Department.all


  .row
    .col-md-6.col-md-offset-3
      .form-inputs
        = f.input :shift
        = f.input :start_at
        = f.input :collect_mins
        = f.input :in_mins
        = f.input :out_mins
        = f.input :arrival_mins

      .form-actions
        = f.button :submit

app/views/routings/edit.html.slim
p.text-center 编辑路由
== render 'form'

= link_to '查看', @routing
'|
= link_to '返回', routings_path

app/views/routings/index.html.slim
table.table.table-striped
  thead
    tr
      th 班次
      th 开始时间
      th 揽件时间
      th 入站时间
      th 出站时间
      th 到达时间
      th 起点
      th 终点
      th
      th
      th

  tbody
    - @routings.each do |routing|
      tr
        td = routing.shift
        td = routing.start_at.strftime("%H:%M")
        td = routing.collect_mins
        td = routing.in_mins
        td = routing.out_mins
        td = routing.arrival_mins
        td = routing.start_province.try(:name)
        td = routing.destination_province.try(:name)
        td = link_to 'Show', routing
        td = link_to 'Edit', edit_routing_path(routing)
        td = link_to 'Destroy', routing, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to '新增路由', new_routing_path

app/views/routings/new.html.slim
p.text-center 新增路由

== render 'form'

= link_to '返回', routings_path

app/views/routings/show.html.slim
p#notice = notice

p
  strong Shift:
  = @routing.shift
p
  strong Start at:
  = @routing.start_at
p
  strong Collect mins:
  = @routing.collect_mins
p
  strong In mins:
  = @routing.in_mins
p
  strong Out mins:
  = @routing.out_mins
p
  strong Arrival mins:
  = @routing.arrival_mins
p
  strong Start:
  = @routing.start_province_id
p
  strong Destination:
  = @routing.destination_province_id

= link_to 'Edit', edit_routing_path(@routing)
'|
= link_to 'Back', routings_path