config/routes.rb
Rails.application.routes.draw do
  resources :routings
  resources :timelines
  resources :collect_criterions

  resources :collects do 
    member do 
      get 'timeline'
    end
  end
  resources :criterions
  resources :commissions
  resources :areas do 
    collection do 
      get 'export'
      get 'export_detail'
    end
  end

  resources :stations do 
    member do 
      get 'area'
    end
    collection do 
      get 'export'
    end
  end
  resources :cities do 
    member do 
      get 'map'
    end
  end
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  get  '/operate' => 'home#operate'
  post '/import' => 'home#import'   
  get '/clear' => 'home#clear'   

  authenticated :admin do
    root "admin/keys#index", as: "admin_root"
  end
  authenticated :users do
    root "stations#index", as: "users_root"
  end

  namespace :admin do 
    resources :keys
    resources :stations do 
      collection do 
        get 'syn'
      end 
    end
  end
  mount ApiV1 => "/" 
  mount GrapeSwaggerRails::Engine => '/swagger'
 

end

app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController

  before_action :set_criterion, only: [:show, :edit, :update, :destroy]

  def index
    @criterions = Criterion.all.page params[:page] 
  end
  

  # GET /commissions/1
  def show
  end

  # GET /commissions/new
  def new
    @criterion = Criterion.new
  end

  # GET /commissions/1/edit
  def edit
  end

  # POST /commissions
  def create
    @criterion = Criterion.new(criterion_params)

    if @criterion.save
      redirect_to criterions_path, notice: '标准创建成功。'
    else
      render :new
    end
  end

  # PATCH/PUT /commissions/1
  def update
    if @criterion.update(criterion_params)
      redirect_to criterions_path, notice: '标准更新成功。'
    else
      render :edit
    end
  end

  # DELETE /commissions/1
  def destroy
    @criterion.destroy
    redirect_to criterions_path, notice: '标准删除成功！'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def criterion_params
      params.require(:criterion).permit(:id,:name, :step,:ctype, :minutes, :criterionable_id, :criterionable_type)
    end

end

app/views/criterions/_form.html.slim
= simple_form_for(@criterion, html: {class: "form-horizontal"})  do |f|

  = f.error_notification
  .row
    .col-sm-6
      = f.input :ctype
  .row
    .col-sm-6
      = f.input :name
  .row
    .col-sm-6
      = f.input :step



  .row
    .col-sm-6
      = f.input :minutes

  .form-group
      = f.button :submit, "确定"

app/views/criterions/edit.html.slim
.content-wraper
  == render 'form'

  = link_to '返回', criterions_path

app/views/criterions/index.html.slim
.content-wraper
  .row
    .col-sm-12
      p.pull-right 
        = link_to "添加", new_criterion_path, class: "btn btn-primary"
  table.table 
    thead
      tr 
        th 编号
        th 名称
        th 步骤
        th 类型
        th 时长（分）
    tbody 
      - @criterions.each do |criterion|
        tr
          td #{criterion.id} 
          td #{criterion.name} 
          td #{criterion.step} 
          td #{criterion.ctype}
          td #{criterion.minutes}
          td 
           .btn-group
             = link_to  "编辑", edit_criterion_path(criterion), class:"btn btn-warning"
             = link_to "删除", criterion_path(criterion), method: "delete", class: "btn btn-danger", data:{ confirm: '确定删除吗 ?'}

  .row
    .col-lg-12.toolbar
      .pull-right = paginate @criterions, theme: 'twitter-bootstrap-3'

app/views/criterions/new.html.slim
.content-wraper
  == render 'form'

  = link_to '返回', criterions_path