config/routes.rb
Rails.application.routes.draw do
  resources :routings
  resources :timelines
  resources :collect_criterions

  resources :collects do 
    member do 
      get 'timeline'
    end
  end
  resources :criterions
  resources :commissions
  resources :areas do 
    collection do 
      get 'export'
      get 'export_detail'
    end
  end

  resources :stations do 
    member do 
      get 'area'
    end
    collection do 
      get 'export'
    end
  end
  resources :cities do 
    member do 
      get 'map'
    end
  end
  patch '/photos' => 'photos#upload'
  resources :photos, :only => [:index, :create, :destroy, :update] do
    member do
      post 'cover'
    end

  end
  resources :users do 
    member do 
      get 'posts'
    end
  end
  root 'home#index'
  get  '/operate' => 'home#operate'
  post '/import' => 'home#import'   
  get '/clear' => 'home#clear'   

  authenticated :admin do
    root "admin/keys#index", as: "admin_root"
  end
  authenticated :users do
    root "stations#index", as: "users_root"
  end

  namespace :admin do 
    resources :keys
    resources :stations do 
      collection do 
        get 'syn'
      end 
    end
  end
  mount ApiV1 => "/" 
  mount GrapeSwaggerRails::Engine => '/swagger'
 

end

app/models/key.rb
class Key < ActiveRecord::Base
  enum ktype: [:js,:server]
end

app/controllers/admin/keys_controller.rb
class Admin::KeysController < Admin::AdminController

  before_action :set_key, only: [:update,:edit,:destroy]
  def index 
    @keys = Key.all
  end

  def new 
    @key = Key.new
  end

  def edit
    
  end

  def update 
     if @key.update key_params
       redirect_to admin_keys_url
     else
       render :edit
     end
   end

   def create 
     @key = Key.new(key_params) 

     if @key.save
       redirect_to admin_keys_url
     else
       render :new
     end

   end
   def destroy
     @key.destroy
     redirect_to admin_keys_url
   end


   def set_key
     @key = Key.find(params[:id])
   end
   def key_params
     params.require(:key).permit(:id,:origin,:api_key, :ktype, :api_secret)
   end

end

app/views/admin/keys/_form.html.slim
= simple_form_for [:admin, @key] do |f|
  = f.error_notification
  = f.input :origin
  = f.input :api_key
  = f.input :ktype, as: :select ,required: true, collection:Key.ktypes.keys.to_a
  = f.input :api_secret
  = f.button :submit, class: "btn btn-primary"

app/views/admin/keys/edit.html.slim
= render "form"

app/views/admin/keys/index.html.slim
p
  = link_to "添加", new_admin_key_url, class: "btn btn-primary"
.row 
  .col-md-12 
    table.table 
     tr 
       th #id
       th 域
       th api key
       th api secret
       th api type
       th 操作
     - @keys.each do |key| 
       tr
         th #{key.id}
         td #{key.origin} 
         td #{key.api_key} 
         td #{key.api_secret} 
         td #{key.ktype} 
         td 
           .btn-group
             = link_to  "编辑", edit_admin_key_url(key), class:"btn btn-warning"
             = link_to '删除', admin_key_url(key),class:"btn btn-danger", data: {:confirm => '确定删除吗？'}, :method => :delete

app/views/admin/keys/new.html.slim
= render "form"